name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --logger "trx;LogFileName=result.trx"
    - name: Publish Unit Test Results
      uses: dorny/test-reporter@v1
      if: success()    # run this step even if previous step failed
      with:
        name: Xunit Tests            # Name of the check run which will be created
        path: Test/TestResults/result.trx    # Path to test results
        reporter: dotnet-trx        # Format of test results
    - name: Run .NET Code Analysis
      uses: dotnet/code-analysis@main
      id: code-analysis
      with:
        build-breaking: false
    - name: Upload sarif file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: .gdn\analysis_results.sarif
